server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always
    include-exception: true

spring:
  swagger:
    base-url: http://localhost:8080

logging:
  level:
    org.sopt: debug
    org.springframework.web: info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  override-with-generic-response: false

member:
  file:
    path: data/members.csv
